### ISSUE TITLE
What is the Objective

### ISSUE THREAD

**Issue by brettforbes** [OTRF/GenAI-Security-Adventures#1]
Hi Roberto,

Brett here from Australia, we are connected on typeDB Discord.

Things have moved ahead for us, and i am super interested in using LLM-approaches for ATT&CK. But to me it is not yet clear that prompt engineering is the right way to go, since it can not include the entire Mitre ATT&CK database. So the issue is, whether it is a context thing, or a training thing (e.g. nanogpt).

But one point I am really interested in is what are some use case examples, where we can imagine using ChatGPT and ATT&CK knowledge to provide an answer? What scenarios do you envisage? Can you help by expanding on these?

Is it:
-  a reference thing? for example, please explain TTP1234?
- a knowledge thing? for example, what are the tools or groups who use TTP1234?
- a causal thing? for example, I have an email that is suspicious, what is the TTP for it?
- etc.

I'm actually thinking prompt engineering/context is insufficient, and i am interested in training.

But, it would to really useful to first start to understand all of the use case variations. Can you offer any ideas?

**Comment by brettforbes** [comment]
actually i have also seen some other interesting capabilities, like
- autogpt, and
- claude

which may be better, plus i am still trying to check out open source, can we talk?

**Comment by priamai** [comment]
Maybe we could produce TRAM2 where the entity extraction is performed via a GPT model?
TRAM: https://github.com/center-for-threat-informed-defense/tram/

Ideally I would like to have a system that given a textual report, can produce a full STIX bundle with all the SDO,SRO and ATT&CK object.

Something like the Anomali Lens but way more accurate: https://www.anomali.com/products/lens

**Comment by Cyb3rWard0g** [comment]
Hello @brettforbes ! It has been a while :) First, it is important to understand that this repository is to share experiments only. Official implementation of each use case in more details will be available in the https://github.com/OTRF org. Next, as we know, the use of retrieval augmentation and Q&A can be applied to any type of information that the model is not aware of (it was not trained on it or private documents). One security use-case that I wanted to share regarding retrieval augmentation and Q&A is how we can take those concepts and query threat intelligence information via natural language. There are organizations that collect their own threat intelligence and usually store it in a database (SQL, Graph, etc.). I wanted to show an example of that, so I picked ATT&CK groups as an example of documentation of threat actors mapped to adversary tradecraft (ATT&CK at least gives you ATT&CK techniques and procedures). This is a good implementation to ask questions about adversary tradecraft without relying on keyword search and with specific context. we use the LLM to summarize our relevant documents after the query/prompt is used by the threat intelligence analyst. That is the "Objective" here. I will release ATTCK-GPT V1 with that idea behind.

**Comment by Cyb3rWard0g** [comment]
Hello @priamai ! yes, we are also working on it as an experiment to share with the community. stay tuned ;)
